version: '3.1'

services:
  motherbase:
    image: 127.0.0.1:5000/motherbase
    build: motherbase
    ports:
      - 1337:1337
    environment:
      DATABASE_URL: "mongodb://root:aJM3NQV9qSc7gZ3ijNpLTKci0O9TuTxRmvOpFAtkx3AZU6LAq4SWYiBIRPY8oTTj@pixel-db:27017"

  client:
    image: 127.0.0.1:5000/client
    build: client
    deploy:
      mode: global

  pixel-db:
    image: mongo
    restart: always
    ports:
      - 27017:27017

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: aJM3NQV9qSc7gZ3ijNpLTKci0O9TuTxRmvOpFAtkx3AZU6LAq4SWYiBIRPY8oTTj

  pixel-db-monitor:
    image: mongo-express
    restart: always

    ports:
      - 8081:8081

    environment:
      ME_CONFIG_MONGODB_SERVER: pixel-db
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: aJM3NQV9qSc7gZ3ijNpLTKci0O9TuTxRmvOpFAtkx3AZU6LAq4SWYiBIRPY8oTTj

  pixel-proxy:
    image: 127.0.0.1:5000/pixel-proxy
    build: pixel-proxy
    ports:
      - 80:80
      - 443:443
    depends_on:
      - pixel-db-monitor
